server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  bus:
    trace:
      enabled: true  # 开启消息跟踪
  rabbitmq:
    host: 47.104.222.78
    port: 5672
    username: lgh
    password: lgh
env: testerererer3434343343


